# HX7A75A / XC7A75T-FGG484-2 dedicated constraints.
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property PACKAGE_PIN Y18 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
create_clock -name sys_clk -period 20.000 [get_ports sys_clk]

set_property PACKAGE_PIN E3  [get_ports {key_n[0]}]
set_property PACKAGE_PIN G4  [get_ports {key_n[1]}]
set_property PACKAGE_PIN P19 [get_ports {key_n[2]}]
set_property PACKAGE_PIN R19 [get_ports {key_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_n[*]}]
set_property PULLUP true [get_ports {key_n[*]}]
set_property PACKAGE_PIN N14 [get_ports {sw[0]}]
set_property PACKAGE_PIN P16 [get_ports {sw[1]}]
set_property PACKAGE_PIN R17 [get_ports {sw[2]}]
set_property PACKAGE_PIN N15 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[*]}]

# The connected keypad presents its column group on P2IO[0:3] and row group
# on P2IO[4:7]. Swapping the FPGA port roles here corrects the observed
# transposed key matrix without changing the physical ribbon cable.
set_property PACKAGE_PIN V2 [get_ports {keypad_row_n[0]}]
set_property PACKAGE_PIN R3 [get_ports {keypad_row_n[1]}]
set_property PACKAGE_PIN R2 [get_ports {keypad_row_n[2]}]
set_property PACKAGE_PIN W2 [get_ports {keypad_row_n[3]}]
set_property PACKAGE_PIN T3 [get_ports {keypad_col_n[0]}]
set_property PACKAGE_PIN T1 [get_ports {keypad_col_n[1]}]
set_property PACKAGE_PIN U1 [get_ports {keypad_col_n[2]}]
set_property PACKAGE_PIN U2 [get_ports {keypad_col_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_row_n[*] keypad_col_n[*]}]
set_property PULLUP true [get_ports {keypad_row_n[*]}]

set_property PACKAGE_PIN AB18 [get_ports {seg_n[0]}]
set_property PACKAGE_PIN U17  [get_ports {seg_n[1]}]
set_property PACKAGE_PIN U18  [get_ports {seg_n[2]}]
set_property PACKAGE_PIN P14  [get_ports {seg_n[3]}]
set_property PACKAGE_PIN R14  [get_ports {seg_n[4]}]
set_property PACKAGE_PIN R18  [get_ports {seg_n[5]}]
set_property PACKAGE_PIN T18  [get_ports {seg_n[6]}]
set_property PACKAGE_PIN N17  [get_ports {seg_n[7]}]
set_property PACKAGE_PIN AA18 [get_ports {seg_sel[0]}]
set_property PACKAGE_PIN W17  [get_ports {seg_sel[1]}]
set_property PACKAGE_PIN V17  [get_ports {seg_sel[2]}]
set_property PACKAGE_PIN AB20 [get_ports {seg_sel[3]}]
set_property PACKAGE_PIN AA19 [get_ports {seg_sel[4]}]
set_property PACKAGE_PIN V19  [get_ports {seg_sel[5]}]
set_property PACKAGE_PIN V18  [get_ports {seg_sel[6]}]
set_property PACKAGE_PIN Y19  [get_ports {seg_sel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_n[*] seg_sel[*]}]

set_property PACKAGE_PIN AA6 [get_ports {led[0]}]
set_property PACKAGE_PIN V7  [get_ports {led[1]}]
set_property PACKAGE_PIN W7  [get_ports {led[2]}]
set_property PACKAGE_PIN AB7 [get_ports {led[3]}]
set_property PACKAGE_PIN P20 [get_ports buzzer_n]
set_property IOSTANDARD LVCMOS33 [get_ports {led[*] buzzer_n}]

set_property PACKAGE_PIN M20 [get_ports flash_cs_n]
set_property PACKAGE_PIN K13 [get_ports flash_hold_n]
set_property PACKAGE_PIN M13 [get_ports flash_miso]
set_property PACKAGE_PIN K14 [get_ports flash_sclk]
set_property PACKAGE_PIN K17 [get_ports flash_wp_n]
set_property PACKAGE_PIN L13 [get_ports flash_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_cs_n flash_hold_n flash_miso flash_sclk flash_wp_n flash_mosi}]

set_property PACKAGE_PIN F15 [get_ports camera_scl]
set_property PACKAGE_PIN F13 [get_ports camera_sda]
set_property PACKAGE_PIN F14 [get_ports {camera_data[0]}]
set_property PACKAGE_PIN F16 [get_ports {camera_data[1]}]
set_property PACKAGE_PIN E17 [get_ports {camera_data[2]}]
set_property PACKAGE_PIN C14 [get_ports {camera_data[3]}]
set_property PACKAGE_PIN C15 [get_ports {camera_data[4]}]
set_property PACKAGE_PIN E13 [get_ports {camera_data[5]}]
set_property PACKAGE_PIN E14 [get_ports {camera_data[6]}]
set_property PACKAGE_PIN E16 [get_ports {camera_data[7]}]
set_property PACKAGE_PIN D16 [get_ports camera_pwdn]
set_property PACKAGE_PIN D14 [get_ports camera_xclk]
set_property PACKAGE_PIN D15 [get_ports camera_vsync]
set_property PACKAGE_PIN B15 [get_ports camera_href]
set_property PACKAGE_PIN B16 [get_ports camera_reset_n]
set_property PACKAGE_PIN C13 [get_ports camera_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_scl camera_sda camera_data[*] camera_pwdn camera_xclk camera_vsync camera_href camera_reset_n camera_pclk}]

set_property PACKAGE_PIN T14 [get_ports {hdmi_data_p[0]}]
set_property PACKAGE_PIN W15 [get_ports {hdmi_data_p[1]}]
set_property PACKAGE_PIN T16 [get_ports {hdmi_data_p[2]}]
set_property PACKAGE_PIN T15 [get_ports {hdmi_data_n[0]}]
set_property PACKAGE_PIN W16 [get_ports {hdmi_data_n[1]}]
set_property PACKAGE_PIN U16 [get_ports {hdmi_data_n[2]}]
set_property PACKAGE_PIN V13 [get_ports hdmi_clk_p]
set_property PACKAGE_PIN V14 [get_ports hdmi_clk_n]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_p[*] hdmi_data_n[*] hdmi_clk_p hdmi_clk_n}]
